### ISSUE TITLE
Broken in IE

### ISSUE THREAD

**Issue by closacco** [teamcolors/teamcolors.github.io#47]
Not sure if worth fixing @jimniels...

**Comment by jimniels** [comment]
Which IE in specific are you referring to? 8? 9? 10? Haven't looked at the site ever in IE...

**Comment by closacco** [comment]
IE11: ![IE Screenshot](https://cloud.githubusercontent.com/assets/308120/8725422/254ad948-2ba2-11e5-8556-622176cc5a7f.png)

**Comment by jimniels** [comment]
Nice catch. A dubious jQuery insertion method has been fixed. Now it should work in IE and everywhere else.

**Comment by closacco** [comment]
Success:

![screen shot 2015-07-27 at 1 14 56 pm](https://cloud.githubusercontent.com/assets/308120/8912571/88683c6a-3461-11e5-9534-eee3461e1447.png)
