### ISSUE TITLE
MLB official (?) colors

### ISSUE THREAD

**Issue by myshkin** [teamcolors/teamcolors.github.io#50]
Craig Robinson lists Pantone codes for all the team colors in a 2012 infographic, supposedly derived from the MLB pressbox website: http://flipflopflyin.com/flipflopflyball/gb13.html

**Comment by jimniels** [comment]
Thanks for the link!

Accurate, up-to-date MLB colors have been a little more difficult to find, even on the MLB press box site. I'm currently in contact with someone at mlb.com, so hopefully they can point me in the right direction and we will be able to include accurate, up-to-date info on the site.

If not, i'll consider adding this older info. I'll post again when I have more info.

**Comment by jimniels** [comment]
@CATColor1 can you tell me your source for those official colors? Mostly I'm interested because I was able to get official RGB logo slicks from MLB Style Guide. These logo slicks don't provide exact color values, but through an image editing program you can inspect the colors and discover their values. These were the RGB values for the Mariners:

```
#0C2C56 (dark blue)
#005C5C (dark green)
#C4CED4 (gray)
#FFFFFF (white)
```

It seems like the best thing to do in this case is extract these colors values from the logo slicks, and then put those into the site and cite MLB Style Guide as the source.

See attached files:
[NL Primary Marks - RGB Digital Art.pdf](https://github.com/teamcolors/teamcolors.github.io/files/6813/NL.Primary.Marks.-.RGB.Digital.Art.pdf)
[AL Primary Marks - RGB Digital Art.pdf](https://github.com/teamcolors/teamcolors.github.io/files/6814/AL.Primary.Marks.-.RGB.Digital.Art.pdf)

**Comment by CATColor1** [comment]
Can you get official Style Guides from MLB Style Guide? This would be really helpful.

**Comment by CATColor1** [comment]
Can you obtain the Style Guides for all 30 teams from MLB Style Guide? That would be really helpful. My color information came from 
http://mlb.mlb.com/mlb/events/all_star/y2015/franchise_four.jsp, but if you could gain access to and provide the Style Guides for all 30 teams, that would supersede what I've provided (and be official). I've tried attaching the 2015 Seattle Mariners Style Guide, but there's an issue with attachments, so I can't at the moment attach it. If there's a way to attach it, I would immediately do so.

**Comment by jimniels** [comment]
I wish I could, but I can't seem to find style guides that specify color values anywhere on MLB Style Guide. Here's what they offer:

![screen shot 2015-10-02 at 9 47 15 am](https://cloud.githubusercontent.com/assets/1316441/10250860/9b4d45ec-68ea-11e5-8b87-edcf4a629e53.png)

Under MLB downloads are the logo marks for the league itself.

Under Club Downloads you'll find what the screenshot describes: primary and 3d marks for all 30 teams, but there is no 'style guide' for the teams, just the logos themselves in RGB format.

I can't find anywhere that gives you style guides. At the bottom of the logo slick PDF I posted, you'll see it says "See club pages for color information"

<img width="927" alt="screen shot 2015-10-02 at 9 49 35 am" src="https://cloud.githubusercontent.com/assets/1316441/10250936/f8bcb6e0-68ea-11e5-9c1d-565ca44ef93c.png">

But I can't find anything on the club pages for color info either. So, at this point, it seems like our best reference is the logo slick PDFs I uploaded earlier. Although, it sounds like you have the official Mariners Style Guide? I'd love to see it if you can send it another way. Unfortunately, it sounds like the style guide you have doesn't match the color info in the logo slick provided by the MLB.

**Comment by CATColor1** [comment]
Is the password publicly available? Or do you have to apply for credentials?

**Comment by jimniels** [comment]
I applied for credentials.

**Comment by CATColor1** [comment]
Could you provide a screenshot of a club page, please?

**Comment by jimniels** [comment]
I'm not entirely sure what the "Club Pages" are, as there is no link to them. But I believe these are them:

![screen shot 2015-10-02 at 10 02 37 am](https://cloud.githubusercontent.com/assets/1316441/10251268/ba6f6e58-68ec-11e5-8658-9e1094af8cd1.png)


This is such a bummer, because I feel sooooo close to have the official colors, but I can't quite find them. The MLB provides the colors on their guide:

![screen shot 2015-10-02 at 9 58 38 am](https://cloud.githubusercontent.com/assets/1316441/10251142/2c3cf72c-68ec-11e5-9d9d-fef67f2695b0.png)

But none of the team guides that I can find provide that.

**Comment by CATColor1** [comment]
Yeah, I feel bummed out, too. If there was a way to upload the Mariners' Style Guide, I'd do it, but every time I try it says "Something went really wrong, and we can't process that file. Try again." I try again, and get the same message. I guess we'll just have to go by the RGB logo slicks until something emerges.

**Comment by jimniels** [comment]
Ahh, I found the Mariners guide. It's on a site separate from the MLB style guide/press box site.

<img width="916" alt="screen shot 2015-10-02 at 10 15 43 am" src="https://cloud.githubusercontent.com/assets/1316441/10251534/931ace68-68ee-11e5-93bb-67aea75961dc.png">

Is that what you have?

**Comment by CATColor1** [comment]
No. The style guide I have has uniforms. Where did you find this? Can you find something similar for all 30 teams? That might work here.

**Comment by jimniels** [comment]
Nope, I can't find it for all the teams. It's not available via the standardized MLB site information architecture. I found this via the Mariner's own private site, which they provided login info via their press box site. It's kind of a big mess out there.

**Comment by CATColor1** [comment]
Well, that's too bad. I e-mailed the Mariners, and they sent it to me. I've attached a screenshot.
![yahoo mail screenshot](https://cloud.githubusercontent.com/assets/13282266/10251743/3cae70be-68f0-11e5-977e-1b3f828f3803.png)

**Comment by CATColor1** [comment]
I e-mailed the Mariners, and they sent their style guide. Here's a screenshot of what the colors are according to that: 
![yahoo mail screenshot](https://cloud.githubusercontent.com/assets/13282266/10251846/eda0dc22-68f0-11e5-8054-17b49bdb0ae9.png)

**Comment by CATColor1** [comment]
Is there a publicly available password for MLB Pressbox (Not MLB Style Guide)?

**Comment by jimniels** [comment]
Not that I know of...

**Comment by myshkin** [comment]
Given [the inconsistencies in team logos](http://espn.go.com/mlb/story/_/id/10927272/uni-watch-mismatched-mlb-logos), I wouldn't be surprised if uniform colors didn't always match logo colors. I pinged Paul Lukas on Twitter to see if he could help.

**Comment by CATColor1** [comment]
@jimniels So, I found this on MLBPressbox.com: http://pressbox.mlb.com/pressbox_open/help/index.jsp. If you have credentialed access to a team's site, I think you could click on a team's "Logos and Headshots" tab, like in the attached screenshot: 
![mlbpressbox - ny yankees](https://cloud.githubusercontent.com/assets/13282266/10264675/7bc63058-69d0-11e5-9f69-d16dd2a01896.png)
If that doesn't work, then maybe we should wait for Lukas' response. I have sent him tweets, and he's told me that MLB lists colors by Pantone, not RGB. This would be my recommendation for how to determine individual MLB team colors. Feel free to message me if official color source information emerges in the future.

**Comment by jimniels** [comment]
Yeah I've clicked here, there's nothing useful there. There's a link to the MLB style guide site (which doesn't provide individual team colors) and then there are links to player shots which are of no use either. 

I would guess that teams have official Pantone colors as well as digital colors but the MLB doesn't seem to have a standardized place for hosting these like other leagues do.

**Comment by myshkin** [comment]
I should note that the link I mentioned in the original post is supposedly derived from 2012 official Pantone colors, from the MLB Pressbox website. I'd be inclined to take Craig Robinson at his word, but of course we don't know whether anything has changed since 2012.

**Comment by jimniels** [comment]
It seems like unless we can find citable sources for this information, the current colors seem sufficient.
