### ISSUE TITLE
Source for EPL, MLB, MLS, NHL?

### ISSUE THREAD

**Issue by swanson** [teamcolors/teamcolors.github.io#54]
For leagues/teams with no official colors, is there a source for the approximations?

I came across this link: http://www.glidden.com/Team-Colors and was wondering if those values would be 'better' than the current values.

> Score the official paint colors of your favorite sports teams. Team Colors paints are **perfect matches to college and professional sports teams’ colors**, and are available from Glidden® paint at The Home Depot®.

Looks like the RGB values can be extracted from the individual swatches. I'd be interested in helping out on this if there is interest.

**Comment by jimniels** [comment]
There is no documented source for the unofficial color approximations. Many have been extracted from Wikipedia, some are submitted by individual users on Github, and so forth.

I kind of like the idea of sourcing all "unofficial" colors from one place, but I'm a little hesitant of using Glidden's site. These appear to be paint colors, and physical world colors (like CMYK and Pantone) always appear less rich and dynamic when translated directly to screen based colors. In other words, if you take a CMYK value and translate it directly to a screen color, like RGB, it always ends up looking a little more washed out than the hand-picked screen color value. See this side-by-side comparison:

![screen shot 2015-12-01 at 9 19 44 am](https://cloud.githubusercontent.com/assets/1316441/11506553/3d1974ee-980d-11e5-9c7b-e9b66d0d9513.png)

For that reason, I'm not sure I would like to pull RGB values straight from Glidden's site, unless we could get more information on *how* exactly they chose the values they are representing on their website.

**Comment by swanson** [comment]
Good point, I see what you mean about the washed out color.

Closing for now, will update if I find anything better.
