### ISSUE TITLE
Brazilian Series A and B

### ISSUE THREAD

**Issue by cassiocardoso** [teamcolors/teamcolors.github.io#56]
Is there any interest in adding brazilian soccer teams? Specifically from 1st and 2nd divisions?

If you think that's relevant I would like to contribute with this.

**Comment by jimniels** [comment]
I wouldn't necessarily see anything against it. I'm not that familiar with Brazilian soccer leagues ... where would you source the color information from?

**Comment by cassiocardoso** [comment]
I would primarily use the teams official websites. If I can't find the information there I would use CBF official website and as a last resource the Wikipedia.

**Comment by jimniels** [comment]
If you want to put together a PR for this, go for it. If possible, try to find official color sources. If you can't, just note that they are approximations (see the README to see how I've done this with other leagues). Oh, and one more thing: i'm not familiar with Brazilian soccer leagues, but I think for now I'm trying to keep this resource limited to professional, top-tier leagues. So, at least for now, don't bother adding any "minor" leagues.

**Comment by jimniels** [comment]
Haven't seen any action on this, so closing it...
